School/ViewModels/Wallet/TopupWalletViewModel.cs
using ACM.Helpers.EmailServiceFactory;
using ACM.Helpers.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using PayFast;

namespace ACM.ViewModels.Wallet
{
    public class TopupWalletViewModel
    {
        internal AppDBContext _context;
        internal IEmailService _emailService;
        internal SecurityOptions _securityOptions;
        internal ClaimsPrincipal _user;
        internal IStringLocalizer<SessionStringLocalizer> _localizer;
        internal string _errorMessage = "";

        public string SelectedWalletAmount { get; set; }
        public double CustomAmount { get; set; }

        public List<SelectListItem> WalletAmountsList { get; set; }

        internal async Task PopulateList()
        {
            WalletAmountsList = new List<SelectListItem>()
            {
                new SelectListItem(){ 
                    Text = "R 50",
                    Value = "50.00"
                },
                new SelectListItem(){
                    Text = "R 100",
                    Value = "100.00"
                },
                new SelectListItem(){
                    Text = "R 200",
                    Value = "200.00"
                },
                new SelectListItem(){
                    Text = "R 500",
                    Value = "500.00"
                },
                new SelectListItem(){
                    Text = "R 1000",
                    Value = "1000.00"
                },
                new SelectListItem(){
                    Text = "R 1500",
                    Value = "1500.00"
                },
                new SelectListItem(){
                    Text = _localizer[PublicEnums.LocalizationKeys.Custom_Amount].Value,
                    Value = "CUSTOM_AMOUNT"
                }
            };
        }

        internal async Task<string> GetPaymentUrl()
        {
            string redirectUrl = "/";

            UserHelperFunctions userHelper = new UserHelperFunctions()
            {
                _context = _context,
                _emailService = _emailService,
                _securityOptions = _securityOptions,
                _user = _user
            };
            userHelper.Populate();

            string passPhrase = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_PASSPHRASE.ToString()).ConfigValue;
            string merchantId = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_MERCHANTID.ToString()).ConfigValue;
            string merchantKey = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_MERCHANTKEY.ToString()).ConfigValue;
            string processUrl = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_PROCESSURL.ToString()).ConfigValue;

            var onceOffRequest = new PayFastRequest(passPhrase);

            string returnlink = _securityOptions.WebsiteHostUrl + "/Payments/PaymentCompleted/";
            string cancellink = _securityOptions.WebsiteHostUrl + "/Payments/TopupWallet?isCancelled=true";
            string notifylink = _securityOptions.WebsiteHostUrl + "/Payments/PaymentITN/";

            // Merchant Details
            onceOffRequest.merchant_id = merchantId;
            onceOffRequest.merchant_key = merchantKey;
            onceOffRequest.return_url = returnlink;
            onceOffRequest.cancel_url = cancellink;
            onceOffRequest.notify_url = notifylink;

            // Buyer Details
            onceOffRequest.email_address = userHelper.user.EmailAddress;

            // Transaction Details
            onceOffRequest.m_payment_id = Guid.NewGuid().ToString();
            onceOffRequest.custom_str1 = userHelper.loggedInUserID.ToString();

            if (SelectedWalletAmount != "CUSTOM_AMOUNT")
            {
                onceOffRequest.amount = double.Parse(SelectedWalletAmount);
            }
            else
            {
                onceOffRequest.amount = CustomAmount;
            }

            onceOffRequest.item_name = "ACM Wallet Topup";
            //onceOffRequest.item_description = "";

            // Transaction Options
            onceOffRequest.email_confirmation = false;
            onceOffRequest.confirmation_address = "";

            redirectUrl = $"{processUrl}{onceOffRequest.ToString()}";

            return redirectUrl;
        }
    }
}

School/Controllers/PaymentsController.cs
using ACM.Helpers.EmailServiceFactory;
using ACM.Helpers.Localization;
using ACM.ViewModels.Wallet;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;
using PayFast;
using PayFast.AspNetCore;

namespace ACM.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly AppDBContext _context;
        private readonly SecurityOptions _securityOptions;
        private readonly IEmailService _emailService;
        private readonly IStringLocalizer<SessionStringLocalizer> _localizer;
        public PaymentsController(AppDBContext context, IOptions<SecurityOptions> securityOptions, IEmailService emailService, IStringLocalizer<SessionStringLocalizer> localizer)
        {
            _context = context;
            _securityOptions = securityOptions.Value;
            _emailService = emailService;
            _localizer = localizer;
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = PublicEnums.UserRoleList.ROLE_ADMINISTRATOR + "," + PublicEnums.UserRoleList.ROLE_USER)]
        public async Task<IActionResult> TopupWallet(bool isCancelled = false)
        {
            try
            {
                TopupWalletViewModel model = new TopupWalletViewModel();
                model._context = _context;
                model._emailService = _emailService;
                model._securityOptions = _securityOptions;
                model._user = User;
                model._localizer = _localizer;

                await model.PopulateList();
                ViewData.Model = model;
            }
            catch (Exception ex)
            {
                HelperFunctions.Log(_context, PublicEnums.LogLevel.LEVEL_EXCEPTION, "Controllers.PaymentsController.TopupWallet", ex.Message, User, ex);
                ViewBag.Error = _localizer[PublicEnums.LocalizationKeys.Generic_Error_Message].Value;
            }
            if(isCancelled)
            {
                ViewBag.Error = _localizer[PublicEnums.LocalizationKeys.Payment_Cancelled_Pleasee_Try_Again].Value;
            }

            return View();
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = PublicEnums.UserRoleList.ROLE_ADMINISTRATOR + "," + PublicEnums.UserRoleList.ROLE_USER)]
        public async Task<IActionResult> PaymentCompleted()
        {
            return View();
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = PublicEnums.UserRoleList.ROLE_ADMINISTRATOR + "," + PublicEnums.UserRoleList.ROLE_USER)]
        [HttpPost]
        public async Task<IActionResult> TopupWallet(TopupWalletViewModel model)
        {
            try
            {
                model._context = _context;
                model._emailService = _emailService;
                model._securityOptions = _securityOptions;
                model._user = User;
                model._localizer = _localizer;

                var url = await model.GetPaymentUrl();
                if(string.IsNullOrEmpty(model._errorMessage))
                {
                    return Redirect(url);
                }
                else
                {
                    ViewBag.Error = model._errorMessage;
                }
            }
            catch (Exception ex)
            {
                HelperFunctions.Log(_context, PublicEnums.LogLevel.LEVEL_EXCEPTION, "Controllers.PaymentsController.TopupWallet", ex.Message, User, ex);
                ViewBag.Error = _localizer[PublicEnums.LocalizationKeys.Generic_Error_Message].Value;
            }

            await model.PopulateList();
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> PaymentITN([ModelBinder(BinderType = typeof(PayFastNotifyModelBinder))] PayFastNotify payFastNotifyViewModel)
        {
            string passPhrase = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_PASSPHRASE.ToString()).ConfigValue;
            string merchantId = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_MERCHANTID.ToString()).ConfigValue;
            string merchantKey = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_MERCHANTKEY.ToString()).ConfigValue;
            string processUrl = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_PROCESSURL.ToString()).ConfigValue;
            string validateUrl = _context.SystemConfiguration.First(x => x.EventCode == PublicEnums.SystemConfigurationList.KEY_PAYFAST_VALIDATEURL.ToString()).ConfigValue;

            payFastNotifyViewModel.SetPassPhrase(passPhrase);

            var calculatedSignature = payFastNotifyViewModel.GetCalculatedSignature();

            var isValid = payFastNotifyViewModel.signature == calculatedSignature;

            // The PayFast Validator is still under developement
            // Its not recommended to rely on this for production use cases
            var payfastValidator = new PayFastValidator(new PayFastSettings()
            {
                MerchantId = merchantId,
                MerchantKey = merchantKey,
                NotifyUrl = _securityOptions.WebsiteHostUrl + "/Payment/PaymentITN/",
                PassPhrase = passPhrase,
                ProcessUrl = processUrl,
                ValidateUrl = validateUrl,
            }, payFastNotifyViewModel, this.HttpContext.Connection.RemoteIpAddress);

            var merchantIdValidationResult = payfastValidator.ValidateMerchantId();

            var ipAddressValidationResult = await payfastValidator.ValidateSourceIp();

            // Currently seems that the data validation only works for success
            if (payFastNotifyViewModel.payment_status == PayFastStatics.CompletePaymentConfirmation)
            {
                var dataValidationResult = await payfastValidator.ValidateData();

                if (dataValidationResult)
                {
                    string paymentID = payFastNotifyViewModel.m_payment_id;
                    string userID = payFastNotifyViewModel.custom_str1;

                    try
                    {
                        if (!string.IsNullOrEmpty(paymentID) && !string.IsNullOrEmpty(userID))
                        {
                            var user = _context.Users.FirstOrDefault(x => x.UserID == Guid.Parse(userID));
                            if(user != null)
                            {
                                _context.UserPaymentTransactions.Add(new Models.UserModelFactory.UserPaymentTransaction()
                                {
                                    AmountFee = payFastNotifyViewModel.amount_fee,
                                    AmountGross = payFastNotifyViewModel.amount_gross,
                                    AmountNet = payFastNotifyViewModel.amount_net,
                                    PaymentType = PublicEnums.PaymentTypeList.PAYMENT_GATEWAY.ToString(),
                                    TransactionDate = DateTime.UtcNow,
                                    TransactionType = PublicEnums.TransactionType.WALLET_TOPUP.ToString(),
                                    UserID = user.UserID,
                                    PFPaymentID = payFastNotifyViewModel.pf_payment_id,
                                    PFReferenceID = paymentID,
                                    PFPaymentStatus = payFastNotifyViewModel.payment_status,
                                    ItemName = payFastNotifyViewModel.item_name,
                                    UserPaymentTransactionID = Guid.NewGuid()
                                });

                                await _context.SaveChangesAsync();
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        HelperFunctions.Log(_context, PublicEnums.LogLevel.LEVEL_EXCEPTION, "Controllers.PaymentsController.PaymentITN", ex.Message + "|paymentID:" + paymentID + "|UserID:" + userID, User, ex);
                    }
                }
            }

            if (payFastNotifyViewModel.payment_status == PayFastStatics.CancelledPaymentConfirmation)
            {

            }

            return Ok();
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = PublicEnums.UserRoleList.ROLE_ADMINISTRATOR + "," + PublicEnums.UserRoleList.ROLE_USER)]
        public async Task<IActionResult> Transactions()
        {
            try
            {
                TransactionsViewModel model = new TransactionsViewModel();
                model._context = _context;
                model._emailService = _emailService;
                model._securityOptions = _securityOptions;
                model._user = User;
                model._localizer = _localizer;

                await model.PopulateList();
                ViewData.Model = model;
            }
            catch (Exception ex)
            {
                HelperFunctions.Log(_context, PublicEnums.LogLevel.LEVEL_EXCEPTION, "Controllers.PaymentsController.Transactions", ex.Message, User, ex);
                ViewBag.Error = _localizer[PublicEnums.LocalizationKeys.Generic_Error_Message].Value;
            }

            return View();
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = PublicEnums.UserRoleList.ROLE_ADMINISTRATOR + "," + PublicEnums.UserRoleList.ROLE_USER)]
        public async Task<JsonResult> Transactions(TransactionsViewModel model)
        {
            try

School/Views/Payments/PaymentCompleted.cshtml
@inject IStringLocalizer<SessionStringLocalizer> Localizer
@{
    ViewData["Title"] = Localizer[PublicEnums.LocalizationKeys.Payment_Completed];
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts
    {
    <script type="text/javascript">
        $(function () {

        });
    </script>
}
<div>
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">@Localizer[PublicEnums.LocalizationKeys.Payment_Completed]</h3>
            <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a>@Localizer[PublicEnums.LocalizationKeys.Home]</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <a>@Localizer[PublicEnums.LocalizationKeys.Wallet_Topup]</a>
                        </li>
                        <li class="breadcrumb-item active">
                            @Localizer[PublicEnums.LocalizationKeys.Payment_Completed]
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-content collapse show">
                <div class="card-body">
                    @if (!string.IsNullOrEmpty(ViewBag.Error))
                    {
                        <div class="alert alert-danger mb-2" role="alert">
                            <strong>@Localizer[PublicEnums.LocalizationKeys.Alert]!</strong> @ViewBag.Error
                        </div>
                    }
                    else if (!string.IsNullOrEmpty(ViewBag.Success))
                    {
                        <div class="alert alert-success mb-2" role="alert">
                            <strong>@Localizer[PublicEnums.LocalizationKeys.Success]!</strong> @ViewBag.Success
                        </div>
                    }
                    <p>@Localizer[PublicEnums.LocalizationKeys.Payment_Completed_Message]</p>
                </div>
            </div>
        </div>
    </div>
</div>

School/Views/Payments/TopupWallet.cshtml
@model ACM.ViewModels.Wallet.TopupWalletViewModel
@inject IStringLocalizer<SessionStringLocalizer> Localizer
@{
    ViewData["Title"] = Localizer[PublicEnums.LocalizationKeys.Wallet_Topup];
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Scripts
    {
    <script type="text/javascript">
        var pageModel = @Json.Serialize(Model);

        $(function () {

        });

        var detailsApp = new Vue({
            el: '#vue-app',
            data: {
                errors: [],
                messages: [],
                model: pageModel
            },
            methods: {
                SelectAmount: function(item){
                    this.model.selectedWalletAmount = item.value;
                },
                PayNow: function(){
                    if(this.model.selectedWalletAmount != null && this.model.selectedWalletAmount != ''){
                        $("#CustomAmount").val(this.model.customAmount);
                        $("#SelectedWalletAmount").val(this.model.selectedWalletAmount);

                        document.forms[0].submit();
                    }
                    else{
                        this.errors = [];
                        this.errors.push({description: 'Please select an amount to pay'});
                    }
                }
            },
            watch: {
                
            }
        });

    </script>
}
<div id="vue-app">
    <form asp-controller="Payments" asp-action="TopupWallet">
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">@Localizer[PublicEnums.LocalizationKeys.Wallet_Topup]</h3>
            <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a>@Localizer[PublicEnums.LocalizationKeys.Home]</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <a>@Localizer[PublicEnums.LocalizationKeys.Wallet_Topup]</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
       @if (!string.IsNullOrEmpty(ViewBag.Error))
        {
            <div class="alert alert-danger mb-2" role="alert">
                <strong>@Localizer[PublicEnums.LocalizationKeys.Alert]!</strong> @ViewBag.Error
            </div>
        }
        else if (!string.IsNullOrEmpty(ViewBag.Success))
        {
            <div class="alert alert-success mb-2" role="alert">
                <strong>@Localizer[PublicEnums.LocalizationKeys.Success]!</strong> @ViewBag.Success
            </div>
        }
            <div v-if="errors.length > 0" v-for="(error, index) in errors" class="alert alert-danger mb-2" v-cloak>
            {{error.description}}
        </div>
        <div v-if="messages.length > 0" v-for="(message, index) in messages" class="alert alert-success mb-2" v-cloak>
            {{message.description}}
        </div>
        <p>@Localizer[PublicEnums.LocalizationKeys.Wallet_Topup_Instruction]</p>
        <div class="row">
            <div class="col-3" v-for="item in model.walletAmountsList">
                <div :class="['card', 'cursor-pointer', {'border-success': model.selectedWalletAmount == item.value}]" v-on:click="SelectAmount(item)">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media d-flex">
                                <div class="media-body text-left mr-1">
                                    <h6 class="text-muted">@Localizer[PublicEnums.LocalizationKeys.Topup_with]</h6>
                                    <h3 v-if="item.value != 'CUSTOM_AMOUNT'">{{item.text}}</h3>
                                    <input v-if="item.value == 'CUSTOM_AMOUNT'" type="text" class="form-control" v-model="model.customAmount" v-on:focus="SelectAmount(item)">
                                </div>
                                <div class="align-self-center">
                                    <i class="fa fa-money-bill font-large-2 float-right"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions text-right">
            <button type="button" class="btn btn-primary" v-on:click="PayNow()">
                @Localizer[PublicEnums.LocalizationKeys.Pay_Now]
            </button>
        </div>
    </div>
    <input type="hidden" asp-for="CustomAmount" />
    <input type="hidden" asp-for="SelectedWalletAmount" />
    </form>
</div>

School/Views/Payments/Transactions.cshtml
@model ACM.ViewModels.Wallet.TransactionsViewModel
@inject IStringLocalizer<SessionStringLocalizer> Localizer
@{
    ViewData["Title"] = Localizer[PublicEnums.LocalizationKeys.Payment_Transactions];
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
    {
        <script src="~/lib/moment/min/moment.min.js"></script>
    <link href="~/lib/pc-bootstrap4-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/lib/pc-bootstrap4-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/lib/vue-bootstrap-datetimepicker/dist/vue-bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/vue.cool-table.js"></script>
    <script type="text/javascript">
        var pageModel = @Json.Serialize(Model);
        var timerId = null;

        Vue.component(VueCoolTable.name, VueCoolTable);

        Vue.filter('formatDateTime', function (value) {
            if (value) {
                return moment(String(value)).format('YYYY/MM/DD hh:mm:ss A')
            }
        });

        var searchApp = new Vue({
            el: '#vue-app',
            data: {
                errors: [],
                messages: [],
                model: pageModel,
                headers: [
                    { text: '@Localizer[PublicEnums.LocalizationKeys.Transaction_Date]', code: 'TransactionDate', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.Item_Name]', code: 'ItemName', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.Payment_Type]', code: 'PaymentType', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.Transaction_Type]', code: 'TransactionType', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.Amount_Gross]', code: 'AmountGross', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.PF_Payment_ID]', code: 'PFPaymentID', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.PF_Reference_ID]', code: 'PFReferenceID', disableSorting: false },
                    { text: '@Localizer[PublicEnums.LocalizationKeys.PF_Payment_Status]', code: 'PFPaymentStatus', disableSorting: false },
                    ]
            },
            methods: {
                onPageChange: function (pagination) {
                    this.ReloadModel(pagination);
                },
                ReloadModel: function (pagination, callback) {
                    var self = this;

                    var postModel = {
                        Pagination: pagination,
                    };

                    self.$data.model.searchValue = self.$data.searchValue;
                    $.post("/Payments/Transactions", postModel, function (response) {
                        if (response.result) {
                            self.$data.model = response.data;

                            if (callback != null && callback != undefined) {
                                callback();
                            }
                        }
                        else {
                            self.$data.messages = [];
                            self.$data.errors = [];
                            self.$data.errors.push({ description: response.message });
                        }
                    })
                },
                Settime: function (callback) {
                    var self = this;
                    clearTimeout(timerId);
                    timerId = setTimeout(
                        function (d) { return searchApp.ReloadModel(self.$data.model.pagination); },
                        1500
                    );
                },
            },

            watch: {
                
            },
            updated: function () {
            },
            beforeUpdate: function () {
            }
        });
    </script>
}
<div id="vue-app">
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">@Localizer[PublicEnums.LocalizationKeys.Payment_Transactions]</h3>
            <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a>@Localizer[PublicEnums.LocalizationKeys.Home]</a>
                        </li>
                        <li class="breadcrumb-item active">
                            @Localizer[PublicEnums.LocalizationKeys.Payment_Transactions]
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-content collapse show">
                <div class="card-body">
                    @if (!string.IsNullOrEmpty(ViewBag.Error))
                    {
                        <div class="alert alert-danger mb-2" role="alert">
                            <strong>@Localizer[PublicEnums.LocalizationKeys.Alert]!</strong> @ViewBag.Error
                        </div>
                    }
                    else if (!string.IsNullOrEmpty(ViewBag.Success))
                    {
                        <div class="alert alert-success mb-2" role="alert">
                            <strong>@Localizer[PublicEnums.LocalizationKeys.Success]!</strong> @ViewBag.Success
                        </div>
                    }
                    <div v-if="errors.length > 0" v-for="(error, index) in errors" class="alert alert-danger mb-2" v-cloak>
                        {{error.description}}
                    </div>
                    <div v-if="messages.length > 0" v-for="(message, index) in messages" class="alert alert-success mb-2" v-cloak>
                        {{message.description}}
                    </div>
                    <h4 class="form-section"><i class="ft-search"></i> @Localizer[PublicEnums.LocalizationKeys.Search]</h4>
                    <br />
                    <cool-table table-class="table table-striped" :items="model.items" :pagination="model.pagination" :headers="headers" @@pagechange="onPageChange">
                        <template v-slot:body="slotProps">
                            <tr v-for="item in slotProps.rowItems" style="cursor:pointer">
                                <td>{{item.transactionDate | formatDateTime}}</td>
                                <td>{{item.itemName}}</td>
                                <td>{{item.paymentType}}</td>
                                <td>{{item.transactionType}}</td>
                                <td>{{item.amountGross}}</td>
                                <td>{{item.pfPaymentID}}</td>
                                <td>{{item.pfReferenceID}}</td>
                                <td>{{item.pfPaymentStatus}}</td>
                            </tr>
                        </template>
                    </cool-table>
                </div>
            </div>
        </div>
    </div>

</div>